# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c81a9b3cc57b263c32b7229c6fe47b903e637919b912389b8dfc238e6c0c8624e8f89d61a591073d1a63f719d8e2175dd2f9f9f7010f5b9827931414b7126e72

test:
  secret_key_base: 438167e7f48226b04ef7e3ffed4105bf919f6f0e251380fc503c0cd28e58282e82dd5f216ac202da90f10fa43eef5793fc5cd4512eea66a41b4643830e3f95e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
